# Renta bruta media por municipio

In [8]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [9]:
anios = (
    (2013, 'http://www.agenciatributaria.es/AEAT/Contenidos_Comunes/La_Agencia_Tributaria/Estadisticas/Publicaciones/sites/irpfmunicipios/2013/jrubikf6d2fcd70c4d0ec216836abfe9f974b4309c26da4.html'),
    (2014, 'http://www.agenciatributaria.es/AEAT/Contenidos_Comunes/La_Agencia_Tributaria/Estadisticas/Publicaciones/sites/irpfmunicipios/2014/jrubik4e93d46e7e85aa3dd4296c3fb35c28a0723d87a0.html'),
    (2015, 'http://www.agenciatributaria.es/AEAT/Contenidos_Comunes/La_Agencia_Tributaria/Estadisticas/Publicaciones/sites/irpfmunicipios/2015/jrubik1ba3b6ffb879f0b4654305cde4f7da3038a346e9.html')
)

In [10]:
def renta_bruta(url):
    df = pd.read_html(url)[0]
    
    # Cambia el nombre de la primera columna
    df.rename(columns={'Unnamed: 0': 'Municipio'}, inplace=True)
    
    # Elimina el total, comunidades y provincias
    df = df[df['Municipio'].str.match(r'.+-[0-9]{5}')]

    # Elimina el código de provincia
    df['Municipio'] = df['Municipio'].str.split('-').str[0]
    
    return df

In [11]:
dataframes = []

for anio, url in anios:
    df = renta_bruta(url)
    df['Año'] = anio
    dataframes.append(df)
    
datos = pd.concat(dataframes)

datos.reset_index(drop=True)

,Municipio,Titulares,NUMERODECLARACIONES,NUMEROHABITANTES,POSICIONAMIENTORENTA BRUTA MEDIANIVELNACIONAL,POSICIONAMIENTORENTA BRUTA MEDIANIVELAUTONÓMICO,RENTA BRUTA MEDIA,RENTA DISPONIBLEMEDIA,Año
0,Almería,95.335,80.509,193.351,689,39,22.868,18.837,2013
1,Carboneras,3.879,3.051,7.852,1.067,66,20.672,17.294,2013
2,Roquetas de Mar,39.781,34.158,91.682,1.085,67,20.582,17.072,2013
3,Huércal de Almería,8.887,7.410,16.663,1.124,71,20.386,17.150,2013
4,Vera,6.321,5.296,15.018,1.167,73,20.202,16.861,2013
5,Macael,2.872,2.151,5.719,1.385,102,19.160,16.094,2013
6,Mojácar,2.484,2.153,6.838,1.465,110,18.766,15.823,2013
7,Tíjola,1.660,1.302,3.776,1.512,113,18.534,15.841,2013
8,Huércal,8.846,7.422,18.374,1.579,123,18.236,15.507,2013
9,Olula del Río,3.032,2.312,6.387,1.636,134,18.047,15.389,2013
10,Fines,919,693,2.203,1.659,139,17.914,15.305,2013
11,Garrucha,3.821,3.120,8.632,1.722,148,17.675,15.121,2013
12,Pechina,1.636,1.336,3.849,1.741,152,17.575,15.039,2013
13,Viator,2.478,2.022,5.605,1.770,158,17.445,15.113,2013
14,Albox,4.965,4.042,11.715,1.774,160,17.431,14.924,2013
15,Benahadux,2.093,1.668,4.220,1.810,167,17.289,14.954,2013
16,Pulpí,4.404,3.811,8.562,1.857,178,17.073,14.636,2013
17,Gádor,1.193,944,3.096,1.891,184,16.933,14.639,2013
18,Serón,992,802,2.218,1.895,185,16.922,14.578,2013
19,Purchena,720,578,1.662,2.012,208,16.531,14.260,2013
20,"Gallardos, Los",1.178,969,3.126,2.033,211,16.453,14.175,2013
21,Cuevas del Almanzora,6.143,5.110,13.737,2.035,212,16.452,14.211,2013
22,Alhama de Almería,1.704,1.350,3.753,2.129,233,16.138,14.156,2013
23,Antas,1.558,1.248,3.161,2.155,240,16.037,13.909,2013
24,Vélez,3.688,3.052,6.791,2.159,242,16.022,13.940,2013
25,Berja,6.663,5.321,15.323,2.181,247,15.898,13.813,2013
26,Adra,11.144,8.941,24.782,2.186,248,15.871,13.755,2013
27,Cantoria,1.444,1.140,3.617,2.212,254,15.785,13.809,2013
28,Dalías,1.925,1.567,3.979,2.215,255,15.774,13.744,2013
29,"Ejido, El",35.566,29.664,84.144,2.232,258,15.725,13.531,2013
...,...,...,...,...,...,...,...,...,...
8819,Atzeneta Albaida,646,518,1.153,1.960,264,17.034,14.922,2015
8820,Pedralba,1.438,1.189,2.813,1.994,268,16.897,14.795,2015
8821,Albalat de la Ribera,2.052,1.701,3.431,2.010,271,16.861,14.609,2015
8822,Quatretonda,1.380,1.127,2.338,2.034,275,16.778,14.531,2015
8823,Benifairó de les Valls,1.309,1.172,2.218,2.038,276,16.768,14.577,2015
8824,Navarrés,1.769,1.464,3.056,2.067,281,16.669,14.636,2015
8825,Rotglà i Corberà,615,528,1.123,2.082,282,16.595,14.459,2015
8826,Anna,1.591,1.294,2.678,2.101,283,16.503,14.564,2015
8827,Chella,1.302,1.060,2.530,2.112,284,16.450,14.483,2015
8828,Mogente/Moixent,2.582,2.007,4.378,2.119,287,16.429,14.397,2015
8829,Camporrobles,698,571,1.255,2.155,289,16.315,14.490,2015
8830,Vallada,1.759,1.414,3.089,2.165,291,16.281,14.276,2015
8831,Sinarcas,691,563,1.148,2.171,293,16.252,14.402,2015
8832,Gavarda,618,521,1.089,2.177,294,16.219,14.132,2015
8833,Tuéjar,613,496,1.193,2.198,296,16.133,14.234,2015
8834,Sumacàrcer,687,571,1.140,2.203,297,16.108,14.282,2015
8835,Senyera,670,575,1.172,2.219,298,16.038,14.051,2015
8836,Massalavés,889,738,1.571,2.242,300,15.922,13.908,2015
8837,"Pobla del Duc, la",1.531,1.318,2.564,2.249,301,15.883,13.982,2015
8838,Antella,766,640,1.271,2.255,303,15.871,14.001,2015
8839,Alcàntera de Xúquer,802,696,1.319,2.309,307,15.645,13.826,2015
8840,Bolbaite,795,607,1.369,2.342,309,15.481,13.803,2015
8841,Rafelguaraf,1.459,1.244,2.403,2.355,311,15.429,13.648,2015
8842,Ademuz,541,445,1.137,2.413,312,15.203,13.494,2015
8843,Llutxent,1.399,1.143,2.402,2.438,314,15.099,13.469,2015
8844,Llaurí,682,567,1.212,2.493,316,14.925,13.201,2015
8845,Montesa,728,598,1.227,2.514,317,14.845,13.322,2015
8846,Venta del Moro,707,540,1.299,2.804,319,13.465,12.327,2015
8847,Ceuta,35.399,28.425,84.519,111,1,30.254,26.815,2015
8848,Melilla,34.534,28.167,86.026,148,1,29.085,25.922,2015