In [22]:
%run INE

In [24]:
datos.head()

,Provincia,Municipio,Ambos sexos-Total-Total,Ambos sexos-Total-Menores de 16 años,Ambos sexos-Total-De 16 a 64 años,Ambos sexos-Total-De 65 y más años,Ambos sexos-españoles-Total,Ambos sexos-españoles-Menores de 16 años,Ambos sexos-españoles-De 16 a 64 años,Ambos sexos-españoles-De 65 y más años,...,Mujeres-Total-De 16 a 64 años,Mujeres-Total-De 65 y más años,Mujeres-españoles-Total,Mujeres-españoles-Menores de 16 años,Mujeres-españoles-De 16 a 64 años,Mujeres-españoles-De 65 y más años,Mujeres-extranjeros-Total,Mujeres-extranjeros-Menores de 16 años,Mujeres-extranjeros-De 16 a 64 años,Mujeres-extranjeros-De 65 y más años
0,Araba/Álava,Dulantzi,2856,694,1875,287,2632,625,1721,286,...,917,148,1281,292,842,147,108,32,75,1
1,Araba/Álava,Amurrio,10260,1530,6658,2072,9655,1399,6198,2058,...,3293,1137,4866,665,3073,1128,299,70,220,9
2,Araba/Álava,Añana,159,9,100,50,151,7,94,50,...,32,34,67,4,29,34,4,1,3,0
3,Araba/Álava,Aramaio,1502,265,935,302,1476,263,911,302,...,433,146,699,130,423,146,11,1,10,0
4,Araba/Álava,Armiñón,234,46,157,31,223,45,147,31,...,76,17,108,20,71,17,5,0,5,0

In [26]:
from pymongo import MongoClient
import json

df = datos

# Conecta a la base de datos
client = MongoClient('localhost', 27017, username=None, password=None)
# Limpia la base de datos
client.drop_database('datos')
db_ine = client['datos']['datos_ine']

# Inserta el dataframe
records = json.loads(df.T.to_json()).values()
db_ine.insert_many(records)

In [29]:
dup = {
    'Provincia': 'Burgos',
    'Municipio': 'Abajas',
    'newcol': 0}

db2 = client['datos']['db2']
db2.insert_one(dup)

### Lee

In [31]:
from pymongo import MongoClient
import pandas as pd

client = MongoClient()
db_poblacion = client['datos']['datos_ine']
db2 = client['datos']['db2']

datos_poblacion = pd.DataFrame.from_records(db_poblacion.find(), exclude=['_id'])
datos_2 = pd.DataFrame.from_records(db2.find(), exclude=['_id'])

datos_poblacion.head()

,Ambos sexos-Total-De 16 a 64 años,Ambos sexos-Total-De 65 y más años,Ambos sexos-Total-Menores de 16 años,Ambos sexos-Total-Total,Ambos sexos-españoles-De 16 a 64 años,Ambos sexos-españoles-De 65 y más años,Ambos sexos-españoles-Menores de 16 años,Ambos sexos-españoles-Total,Ambos sexos-extranjeros-De 16 a 64 años,Ambos sexos-extranjeros-De 65 y más años,...,Mujeres-españoles-De 16 a 64 años,Mujeres-españoles-De 65 y más años,Mujeres-españoles-Menores de 16 años,Mujeres-españoles-Total,Mujeres-extranjeros-De 16 a 64 años,Mujeres-extranjeros-De 65 y más años,Mujeres-extranjeros-Menores de 16 años,Mujeres-extranjeros-Total,Municipio,Provincia
0,1875,287,694,2856,1721,286,625,2632,154,1,...,842,147,292,1281,75,1,32,108,Dulantzi,Araba/Álava
1,6658,2072,1530,10260,6198,2058,1399,9655,460,14,...,3073,1128,665,4866,220,9,70,299,Amurrio,Araba/Álava
2,100,50,9,159,94,50,7,151,6,0,...,29,34,4,67,3,0,1,4,Añana,Araba/Álava
3,935,302,265,1502,911,302,263,1476,24,0,...,423,146,130,699,10,0,1,11,Aramaio,Araba/Álava
4,157,31,46,234,147,31,45,223,10,0,...,71,17,20,108,5,0,0,5,Armiñón,Araba/Álava

In [32]:
datos_poblacion.merge(datos_2, on=['Provincia', 'Municipio'], how='outer')

,Ambos sexos-Total-De 16 a 64 años,Ambos sexos-Total-De 65 y más años,Ambos sexos-Total-Menores de 16 años,Ambos sexos-Total-Total,Ambos sexos-españoles-De 16 a 64 años,Ambos sexos-españoles-De 65 y más años,Ambos sexos-españoles-Menores de 16 años,Ambos sexos-españoles-Total,Ambos sexos-extranjeros-De 16 a 64 años,Ambos sexos-extranjeros-De 65 y más años,...,Mujeres-españoles-De 65 y más años,Mujeres-españoles-Menores de 16 años,Mujeres-españoles-Total,Mujeres-extranjeros-De 16 a 64 años,Mujeres-extranjeros-De 65 y más años,Mujeres-extranjeros-Menores de 16 años,Mujeres-extranjeros-Total,Municipio,Provincia,newcol
0,1875,287,694,2856,1721,286,625,2632,154,1,...,147,292,1281,75,1,32,108,Dulantzi,Araba/Álava,NaN
1,6658,2072,1530,10260,6198,2058,1399,9655,460,14,...,1128,665,4866,220,9,70,299,Amurrio,Araba/Álava,NaN
2,100,50,9,159,94,50,7,151,6,0,...,34,4,67,3,0,1,4,Añana,Araba/Álava,NaN
3,935,302,265,1502,911,302,263,1476,24,0,...,146,130,699,10,0,1,11,Aramaio,Araba/Álava,NaN
4,157,31,46,234,147,31,45,223,10,0,...,17,20,108,5,0,0,5,Armiñón,Araba/Álava,NaN
5,435,183,104,722,413,183,96,692,22,0,...,86,34,296,11,0,6,17,Maeztu,Araba/Álava,NaN
6,665,162,152,979,644,161,152,957,21,1,...,83,66,439,8,1,0,9,Ubarrundia,Araba/Álava,NaN
7,1197,297,346,1840,1141,295,320,1756,56,2,...,177,145,887,27,1,14,42,Artziniega,Araba/Álava,NaN
8,1069,303,258,1630,1003,303,234,1540,66,0,...,174,117,763,31,0,15,46,Asparrena,Araba/Álava,NaN
9,1875,481,590,2946,1839,481,583,2903,36,0,...,249,277,1424,18,0,4,22,Ayala/Aiara,Araba/Álava,NaN
10,192,81,35,308,160,81,29,270,32,0,...,43,15,125,13,0,2,15,Baños de Ebro/Mañueta,Araba/Álava,NaN
11,588,168,147,903,559,167,143,869,29,1,...,80,72,386,13,1,0,14,Barrundia,Araba/Álava,NaN
12,265,126,58,449,252,125,53,430,13,1,...,65,27,208,7,1,2,10,Berantevilla,Araba/Álava,NaN
13,305,146,48,499,296,146,44,486,9,0,...,72,16,194,5,0,1,6,Bernedo,Araba/Álava,NaN
14,657,259,143,1059,612,258,124,994,45,1,...,132,64,465,24,1,11,36,Campezo/Kanpezu,Araba/Álava,NaN
15,437,69,106,612,416,69,104,589,21,0,...,32,48,277,8,0,1,9,Elburgo/Burgelu,Araba/Álava,NaN
16,621,236,148,1005,573,232,129,934,48,4,...,129,72,480,23,2,8,33,Elciego,Araba/Álava,NaN
17,212,87,56,355,185,87,48,320,27,0,...,45,24,155,18,0,6,24,Elvillar/Bilar,Araba/Álava,NaN
18,482,142,121,745,462,141,121,724,20,1,...,64,52,312,6,0,0,6,Erriberagoitia/Ribera Alta,Araba/Álava,NaN
19,128,94,15,237,126,94,15,235,2,0,...,45,6,99,1,0,0,1,Harana/Valle de Arana,Araba/Álava,NaN
20,2214,370,686,3270,2044,363,636,3043,170,7,...,188,336,1477,88,4,15,107,Iruña Oka/Iruña de Oca,Araba/Álava,NaN
21,346,93,75,514,334,93,73,500,12,0,...,41,28,226,7,0,1,8,Gauna,Araba/Álava,NaN
22,109,47,30,186,105,47,30,182,4,0,...,21,11,84,2,0,0,2,Kripan,Araba/Álava,NaN
23,243,90,35,368,237,90,34,361,6,0,...,43,11,152,3,0,1,4,Kuartango,Araba/Álava,NaN
24,925,273,262,1460,824,271,214,1309,101,2,...,124,112,631,54,1,18,73,Labastida/Bastida,Araba/Álava,NaN
25,95,66,7,168,94,66,7,167,1,0,...,30,4,76,0,0,0,0,Lagrán,Araba/Álava,NaN
26,960,308,210,1478,872,307,182,1361,88,1,...,169,75,656,41,1,14,56,Laguardia,Araba/Álava,NaN
27,409,166,106,681,353,166,71,590,56,0,...,82,44,286,27,0,21,48,Lanciego/Lantziego,Araba/Álava,NaN
28,588,195,105,888,554,193,90,837,34,2,...,103,38,370,14,1,5,20,Lantarón,Araba/Álava,NaN
29,533,182,137,852,482,181,116,779,51,1,...,98,49,369,26,0,8,34,Lapuebla de Labarca,Araba/Álava,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8094,150,106,11,267,147,106,11,264,3,0,...,55,6,119,0,0,0,0,Used,Zaragoza,NaN
8095,12532,1982,3952,18466,11281,1950,3652,16883,1251,32,...,1071,1778,8429,658,19,163,840,Utebo,Zaragoza,NaN
8096,45,25,0,70,45,25,0,70,0,0,...,11,0,30,0,0,0,0,Val de San Martín,Zaragoza,NaN
8097,12,16,0,28,12,16,0,28,0,0,...,8,0,15,0,0,0,0,Valdehorna,Zaragoza,NaN
8098,66,47,9,122,66,47,9,122,0,0,...,24,0,45,0,0,0,0,Valmadrid,Zaragoza,NaN
8099,93,52,2,147,77,52,1,130,16,0,...,37,1,69,8,0,0,8,Valpalmas,Zaragoza,NaN
8100,36,32,5,73,25,32,5,62,11,0,...,19,2,33,6,0,0,6,Valtorres,Zaragoza,NaN
8101,136,63,32,231,134,63,32,229,2,0,...,37,11,109,1,0,0,1,Velilla de Ebro,Zaragoza,NaN
8102,63,40,11,114,49,39,7,95,14,1,...,25,2,50,6,1,2,9,Velilla de Jiloca,Zaragoza,NaN
8103,218,135,30,383,203,135,25,363,15,0,...,74,11,175,8,0,2,10,Vera de Moncayo,Zaragoza,NaN
8104,46,29,10,85,45,29,10,84,1,0,...,17,4,38,1,0,0,1,Vierlas,Zaragoza,NaN
8105,38,37,7,82,33,37,7,77,5,0,...,18,4,32,3,0,0,3,Villadoz,Zaragoza,NaN
8106,86,82,16,184,63,82,14,159,23,0,...,46,7,77,10,0,2,12,Villafeliche,Zaragoza,NaN
8107,518,190,121,829,473,190,108,771,45,0,...,112,52,398,20,0,6,26,Villafranca de Ebro,Zaragoza,NaN
8108,57,31,11,99,47,31,11,89,10,0,...,15,9,45,5,0,0,5,Villalba de Perejil,Zaragoza,NaN
8109,209,98,29,336,179,98,21,298,30,0,...,52,9,134,18,0,3,21,Villalengua,Zaragoza,NaN
8110,1817,572,364,2753,1724,568,343,2635,93,4,...,317,163,1298,50,3,10,63,Villamayor de Gállego,Zaragoza,NaN
8111,3083,694,901,4678,2793,687,851,4331,290,7,...,392,402,2126,163,4,25,192,Villanueva de Gállego,Zaragoza,NaN
8112,274,163,36,473,226,163,30,419,48,0,...,89,16,205,18,0,4,22,Villanueva de Huerva,Zaragoza,NaN
8113,24,33,0,57,22,33,0,55,2,0,...,19,0,28,2,0,0,2,Villanueva de Jiloca,Zaragoza,NaN
8114,56,43,11,110,52,43,8,103,4,0,...,22,4,46,2,0,0,2,Villar de los Navarros,Zaragoza,NaN
8115,162,52,28,242,76,52,13,141,86,0,...,27,5,68,34,0,8,42,Villarreal de Huerva,Zaragoza,NaN
8116,253,196,29,478,224,196,26,446,29,0,...,107,8,205,13,0,2,15,Villarroya de la Sierra,Zaragoza,NaN
8117,41,33,2,76,39,33,2,74,2,0,...,18,2,35,0,0,0,0,Villarroya del Campo,Zaragoza,NaN
8118,61,34,5,100,35,34,2,71,26,0,...,20,2,38,8,0,2,10,"Vilueña, La",Zaragoza,NaN
8119,30,18,0,48,30,18,0,48,0,0,...,8,0,18,0,0,0,0,Vistabella,Zaragoza,NaN
8120,293,121,47,461,280,120,41,441,13,1,...,66,19,225,7,1,2,10,"Zaida, La",Zaragoza,NaN
8121,424129,136443,100536,661108,373601,135122,90175,598898,50528,1321,...,79292,43820,312702,24988,815,5048,30851,Zaragoza,Zaragoza,NaN
8122,5373,1242,1363,7978,4229,1227,1078,6534,1144,15,...,658,527,3210,520,10,145,675,Zuera,Zaragoza,NaN
8123,56157,9445,18917,84519,51909,9133,18044,79086,4248,312,...,5172,8844,38957,2147,159,410,2716,Ceuta,Ceuta,NaN